apiVersion: v1
kind: Service
metadata:
  name: identity-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: identity-svc
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8081

